trigger:
  branches:
    include: 
      - 'main'
  paths:
    include: 
      - "**/*.yml"
      - "**/*.py"

variables:
  - group: 'Bundle Deployment Variables'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: deploy
  displayName: 'Deploy bundle'
  steps:
  - checkout: self

  - script: |
      echo "Installing Databricks CLI..."
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/vsts/.bash_profile
      eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      brew tap databricks/tap
      brew install databricks
      databricks bundle deploy
      databricks bundle run sales_job --refresh-all
    displayName: 'Deploy to production and run pipeline update'
    env:
      DATABRICKS_TOKEN: $(token-prod) #Replace with a PAT token for your prod environment
      DATABRICKS_BUNDLE_ENV: 'prod'